//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NikshitPanchal_WebMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_products
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int brand_id { get; set; }
        public int category_id { get; set; }
        public byte[] product_image { get; set; }
        public short model_year { get; set; }
        public decimal list_price { get; set; }
    
        public virtual Tbl_brands Tbl_brands { get; set; }
        public virtual Tbl_categories Tbl_categories { get; set; }
    }
}
